### ISSUE TITLE
No Roku Found

### ISSUE THREAD

**Issue by bgarr33434** [scherererer/skill-roku#2]
installed and added exact serial number in quotes in settingsmeta.json
did not make any entries in mycroft.conf
21:54:46.121 - skill-roku:findRoku:134 - ERROR - No roku found
21:54:46.125 - mycroft.skills.core:load_skill:129 - INFO - Loaded skill-roku
21:54:46.150 - SKILLS - DEBUG - {"type": "register_intent", "data": {"requires": [["skill_rokuShow", "skill_rokuShow"], ["skill_rokuSource", "skill_rokuSource"]], "name": "skill-roku:handle_roku_show_intent", "optional": [], "at_least_one": []}, "context": null}
21:54:46.160 - SKILLS - DEBUG - {"type": "mycroft.skills.loaded", "data": {"modified": 1530395315.329353, "name": "RokuSkill", "id": "skill-roku", "path": "/opt/mycroft/skills/skill-roku"}, "context": null}

**Comment by scherererer** [comment]
Hello, have you opened up a port on the firewall?

[https://github.com/scherererer/skill-roku#mark-1](https://github.com/scherererer/skill-roku#mark-1)

You need to open up ports on the firewall so that your mycroft can discover the roku.

**Comment by bgarr33434** [comment]
I'm using Picroft, not Mark1.  no firewall.  everything on same Lan.  I can discover my Roku from Pycroft using python-roku.  oh, wait.  do I need mycroft.conf swttings?  I did enter the serial number.

**Comment by scherererer** [comment]
You can also try removing the serial number if you've only got one roku. It's only an option in case you have multiple roku's.

I've also pushed a new patch you can try that allows you to specify the IP address manually with a new optional setting: eea9a0fde9fed16c7ed2346c5051287cfabb484b

**Comment by bgarr33434** [comment]
awesome, thank you!

**Comment by bgarr33434** [comment]
I thought for sure that would fix it, but it still cant be found.  I note that you are not importing from roku, and instead using sockets.  here is the log.

Brian Garr@DESKTOP-54ULCFV ~
$ ssh pi@192.168.1.24
pi@192.168.1.24's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Jul  7 19:32:08 2018
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named mycroft.version

***********************************************************************
** Picroft enclosure platform version: 2018-03-14
**
***********************************************************************
This image is designed to make getting started with Mycroft easy.  It
is pre-configured for a Raspberry Pi that has a speaker or headphones
plugged in to the Pi's headphone jack, and a USB microphone.
***********************************************************************
Remote session

***********************************************************************
In a few moments you will see the contents of the speech log.  Hit
Ctrl+C to stop showing the log and return to the command line.  Mycroft
will continue running in the background for voice interaction.

Additional commands you can use from the command line:
    mycroft-cli-client - command line client, useful for debugging
    msm                - Mycroft Skills Manager, install new Skills
    say_to_mycroft     - one-shot commands from the command line
    speak              - say something to the user
    test_microphone    - record and playback to test your microphone
***********************************************************************

^Cpi@picroft:~ cd /var/log
pi@picroft:/var/log $ grep -i roku mycroft-skills.log
19:32:22.090 - git.cmd - DEBUG - Popen(['git', 'config', 'remote.origin.url'], cwd=/opt/mycroft/skills/skill-roku.scherererer, universal_newlines=False, shell=None)
19:34:36.426 - mycroft.skills.core:load_skill:105 - INFO - ATTEMPTING TO LOAD SKILL: skill-roku.scherererer with ID skill-roku.scherererer
19:34:36.852 - mycroft.skills.settings:initialize_remote_settings:144 - DEBUG - settingsmeta.json exist for RokuSkill
19:34:36.856 - mycroft.skills.settings:_request_other_settings:473 - DEBUG - syncing settings with other devices from server for RokuSkill
19:34:37.332 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/52f5bba9-1470-4b5f-819f-915bd7ec7fe9/userSkill?identifier=RokuSkill--f16dbb8e72e2575476490640cbc59fc2 HTTP/1.1" 200 2
19:34:37.346 - mycroft.api:send:115 - DEBUG - Updating etag for: device/52f5bba9-1470-4b5f-819f-915bd7ec7fe9/userSkill?identifier=RokuSkill--f16dbb8e72e2575476490640cbc59fc2
19:34:37.355 - mycroft.skills.settings:_request_my_settings:440 - DEBUG - getting skill settings from server for RokuSkill
19:34:37.813 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererShow", "start": "show"}, "type": "register_vocab", "context": null}
19:34:37.842 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererShow", "start": "play"}, "type": "register_vocab", "context": null}
19:34:37.878 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererSource", "start": "roku"}, "type": "register_vocab", "context": null}
19:34:37.881 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererSource", "start": "netflix"}, "type": "register_vocab", "context": null}
19:34:37.884 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererSource", "start": "amazon"}, "type": "register_vocab", "context": null}
19:34:37.886 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererSource", "start": "youtube"}, "type": "register_vocab", "context": null}
19:34:37.889 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererSource", "start": "tiny desk concerts"}, "type": "register_vocab", "context": null}
19:34:37.891 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererSource", "start": "tunein"}, "type": "register_vocab", "context": null}
19:34:37.894 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererSource", "start": "tune in"}, "type": "register_vocab", "context": null}
19:34:37.896 - SKILLS - DEBUG - {"data": {"end": "skill_roku_schererererSource", "start": "plex"}, "type": "register_vocab", "context": null}
19:34:38.831 - skill-roku_scherererer:findRoku:139 - ERROR - No roku found
19:34:38.836 - mycroft.skills.core:load_skill:129 - INFO - Loaded skill-roku.scherererer
19:34:38.842 - SKILLS - DEBUG - {"data": {"at_least_one": [], "requires": [["skill_roku_schererererShow", "skill_roku_schererererShow"], ["skill_roku_schererererSource", "skill_roku_schererererSource"]], "name": "skill-roku.scherererer:handle_roku_show_intent", "optional": []}, "type": "register_intent", "context": null}
19:34:38.852 - SKILLS - DEBUG - {"data": {"id": "skill-roku.scherererer", "path": "/opt/mycroft/skills/skill-roku.scherererer", "name": "RokuSkill", "modified": 1530983842.1007721}, "type": "mycroft.skills.loaded", "context": null}
19:35:38.531 - mycroft.skills.settings:_request_my_settings:440 - DEBUG - getting skill settings from server for RokuSkill
